services:
  # Backend - Flask API with Direct RapidAPI Integration
  - type: web
    name: ai-airbnb-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn --config gunicorn.conf.py app:app
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: RAPIDAPI_KEY
        value: d8dad7a0d0msh79d5e302536f59cp1e388bjsn65fdb4ba9233
      - key: CORS_ORIGINS
        value: "*"

  # Frontend - React Static Site
  - type: static
    name: ai-airbnb-frontend
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/build
    plan: starter
    region: oregon
    branch: main
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: ai-airbnb-backend
          property: host
      - key: NODE_ENV
        value: production

# Database (if needed in future)
# databases:
#   - name: ai-airbnb-db
#     databaseName: airbnb_search
#     user: airbnb_user
#     plan: starter
